### ISSUE TITLE
Initial GPT3 Prompt 

### ISSUE THREAD

**Issue by ChrisOMills** [brianberns/RedditChatBot#1]
I reviewed your source code and the only prompt I can see is “Reply in the style of a typical Reddit user”.

I tested this some with ChatGPT and the behavior is very different then the results on Reddit. Is there some other prompt or initial setup you gave to make EveryDayChatBot reply like it does in production? 

Sorry to post this as an issue, it’s more of a question.

**Comment by brianberns** [comment]
I think it's because the API lets me give that prompt using the "[system](https://aneejian.com/getting-started-chat-gpt-api-comprehensive-guide/#what-is-role-object-in-messages)" role, which isn't available in the ChatGPT UI.
